services:
  backend01: &backend
    image: leods/rinha-q1-backend
    hostname: backend01
    tty: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    build:
      context: .
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  backend02:
    <<: *backend
    hostname: backend02
    ports:
      - "8081:8080"
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rinhaq1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 30s
      retries: 5
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend01
      - backend02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
volumes:
  db_data: